-- product meta
TRUNCATE product_meta;
INSERT IGNORE INTO product_meta VALUES (1, 'GOLD', 30000, DATE_SUB(NOW(), INTERVAL 5 DAY), DATE_ADD(NOW(), INTERVAL 10 DAY));  -- 진행 중
INSERT IGNORE INTO product_meta VALUES (2, 'SILVER', 50000, DATE_SUB(NOW(), INTERVAL 10 DAY), DATE_ADD(NOW(), INTERVAL 5 DAY));  -- 진행 중, 투자 수량 소진
INSERT IGNORE INTO product_meta VALUES (3, 'NFT', 80000, DATE_SUB(NOW(), INTERVAL 10 DAY), DATE_SUB(NOW(), INTERVAL 2 DAY));  -- 만료, 투자 수량 미소진
INSERT IGNORE INTO product_meta VALUES (4, 'FUND', 100000, DATE_ADD(NOW(), INTERVAL 3 DAY), DATE_ADD(NOW(), INTERVAL 13 DAY));  -- 예정

-- product
TRUNCATE product;
--INSERT IGNORE INTO product VALUES (1, 12000, 1);
--INSERT IGNORE INTO product VALUES (2, 50000, 2);
--INSERT IGNORE INTO product VALUES (3, 75000, 2);
INSERT IGNORE INTO product VALUES (1, 'GOLD', 30000, 12000, 1, DATE_SUB(NOW(), INTERVAL 5 DAY), DATE_ADD(NOW(), INTERVAL 10 DAY));  -- 진행 중
INSERT IGNORE INTO product VALUES (2, 'SILVER', 50000, 50000, 2, DATE_SUB(NOW(), INTERVAL 10 DAY), DATE_ADD(NOW(), INTERVAL 5 DAY));  -- 진행 중, 투자 수량 소진
INSERT IGNORE INTO product VALUES (3, 'NFT', 80000, 75000, 2, DATE_SUB(NOW(), INTERVAL 10 DAY), DATE_SUB(NOW(), INTERVAL 2 DAY));  -- 만료, 투자 수량 미소진
INSERT IGNORE INTO product VALUES (4, 'FUND', 100000, 0, 0, DATE_ADD(NOW(), INTERVAL 3 DAY), DATE_ADD(NOW(), INTERVAL 13 DAY));  -- 예정

-- user's investing
TRUNCATE user_investing;
INSERT IGNORE INTO user_investing VALUES (1234001, 1, 12000, DATE_ADD(NOW(), INTERVAL 1 HOUR));
INSERT IGNORE INTO user_investing VALUES (1234001, 2, 30000, DATE_ADD(NOW(), INTERVAL 1 HOUR));
INSERT IGNORE INTO user_investing VALUES (5678001, 2, 20000, DATE_ADD(NOW(), INTERVAL 1 HOUR));
INSERT IGNORE INTO user_investing VALUES (5678001, 3, 25000, DATE_SUB(NOW(), INTERVAL 3 DAY));
INSERT IGNORE INTO user_investing VALUES (2468001, 3, 50000, DATE_SUB(NOW(), INTERVAL 4 DAY));